name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Set up environment
        uses: jdx/mise-action@v4
        with:
          experimental: true

      - name: Install Dependencies
        run: mise deps

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: mise run changeset:version
          publish: mise run changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          mise exec -- pnpm publish --registry=https://npm.pkg.github.com --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
