name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Set up environment
        uses: jdx/mise-action@v4
        with:
          experimental: true

      - name: Install Dependencies
        run: mise deps

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          version: mise run changeset:version
          publish: mise run changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
